// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Nucleus.DeveloperTools.VisualStudio.Commands
{
    internal sealed partial class Vsix
    {
        public const string Id = "Nucleus.DeveloperTools.VisualStudio.Commands.b8f37620-c532-4e67-be3f-fc4199eaaa54";
        public const string Name = "Nucleus.DeveloperTools.VisualStudio.Commands";
        public const string Description = @"Visual Studio Commands for Nucleus.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Microsoft";
        public const string Tags = "";
    }
}
