// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Nucleus.DeveloperTools.VisualStudio.Commands
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string NucleusCommandsPackageString = "82d43a48-23ee-4279-a0c9-ed8fc4d8d7c5";
        public static Guid NucleusCommandsPackage = new Guid(NucleusCommandsPackageString);

        public const string guidImagesString = "8c0d25f5-d649-4939-82c4-2b8cc988195a";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int NucleusSolutionItemsCommands = 0x0001;
        public const int NucleusProjectCommands = 0x0002;
        public const int AddToPackageCommand = 0x0100;
        public const int AddDependenciesToPackageCommand = 0x0200;
        public const int AddToPackageCommandIcon = 0x0001;
        public const int AddDependenciesToPackageCommandIcon = 0x0002;
    }
}