//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nucleus.DeveloperTools.MSBuild.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nucleus.DeveloperTools.MSBuild.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging.
        /// </summary>
        internal static string NUCL001_CATEGORY {
            get {
                return ResourceManager.GetString("NUCL001_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This project does not contain a valid manifest (package.xml) file..
        /// </summary>
        internal static string NUCL001_MESSAGEFORMAT {
            get {
                return ResourceManager.GetString("NUCL001_MESSAGEFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging.
        /// </summary>
        internal static string NUCL100_CATEGORY {
            get {
                return ResourceManager.GetString("NUCL100_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your manifest (package.xml) file has an empty Id attribute..
        /// </summary>
        internal static string NUCL100_MESSAGEFORMAT {
            get {
                return ResourceManager.GetString("NUCL100_MESSAGEFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging.
        /// </summary>
        internal static string NUCL101_CATEGORY {
            get {
                return ResourceManager.GetString("NUCL101_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your manifest (package.xml) file has an empty name element..
        /// </summary>
        internal static string NUCL101_MESSAGEFORMAT {
            get {
                return ResourceManager.GetString("NUCL101_MESSAGEFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging.
        /// </summary>
        internal static string NUCL102_CATEGORY {
            get {
                return ResourceManager.GetString("NUCL102_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your manifest (package.xml) file has an empty version element..
        /// </summary>
        internal static string NUCL102_MESSAGEFORMAT {
            get {
                return ResourceManager.GetString("NUCL102_MESSAGEFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging.
        /// </summary>
        internal static string NUCL103_CATEGORY {
            get {
                return ResourceManager.GetString("NUCL103_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your manifest (package.xml) file has an invalid Id attribute (value is not a guid)..
        /// </summary>
        internal static string NUCL103_MESSAGEFORMAT {
            get {
                return ResourceManager.GetString("NUCL103_MESSAGEFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging.
        /// </summary>
        internal static string NUCL104_CATEGORY {
            get {
                return ResourceManager.GetString("NUCL104_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your manifest (package.xml) file has an invalid version element.  The version element must contain a version number in the format &apos;major.minor[.build[.revision]]&apos;, where build and revision are optional..
        /// </summary>
        internal static string NUCL104_MESSAGEFORMAT {
            get {
                return ResourceManager.GetString("NUCL104_MESSAGEFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging.
        /// </summary>
        internal static string NUCL105_CATEGORY {
            get {
                return ResourceManager.GetString("NUCL105_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your manifest (package.xml) file does not have a &lt;components&gt; element and will not install anything..
        /// </summary>
        internal static string NUCL105_MESSAGEFORMAT {
            get {
                return ResourceManager.GetString("NUCL105_MESSAGEFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging.
        /// </summary>
        internal static string NUCL106_CATEGORY {
            get {
                return ResourceManager.GetString("NUCL106_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your manifest (package.xml) file does not have any &lt;component&gt; elements and will not install anything..
        /// </summary>
        internal static string NUCL106_MESSAGEFORMAT {
            get {
                return ResourceManager.GetString("NUCL106_MESSAGEFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging.
        /// </summary>
        internal static string NUCL110_CATEGORY {
            get {
                return ResourceManager.GetString("NUCL110_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your manifest (package.xml) file refers to a file &apos;{0}&apos; which does not exist..
        /// </summary>
        internal static string NUCL110_MESSAGEFORMAT {
            get {
                return ResourceManager.GetString("NUCL110_MESSAGEFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging.
        /// </summary>
        internal static string NUCL200_CATEGORY {
            get {
                return ResourceManager.GetString("NUCL200_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your project references version &apos;{1}&apos; of package &apos;{0}&apos; but your manifest (package.xml) file has a compatibility element with a minVersion of {2}, which is less than {1}.  Either update your minVersion to &apos;{1}&apos; or downgrade your reference to &apos;{0}&apos; to version &apos;{2}&apos; or less..
        /// </summary>
        internal static string NUCL200_MESSAGEFORMAT {
            get {
                return ResourceManager.GetString("NUCL200_MESSAGEFORMAT", resourceCulture);
            }
        }
    }
}
