//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nucleus.DeveloperTools.Analyzers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nucleus.DeveloperTools.Analyzers.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your manifest (package.xml) file has an empty Id attribute..
        /// </summary>
        internal static string NUCLEUS100_MESSAGEFORMAT {
            get {
                return ResourceManager.GetString("NUCLEUS100_MESSAGEFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your &lt;package&gt; element id in package.xml.
        /// </summary>
        internal static string NUCLEUS100_TITLE {
            get {
                return ResourceManager.GetString("NUCLEUS100_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your manifest (package.xml) file has an empty name element..
        /// </summary>
        internal static string NUCLEUS101_MESSAGEFORMAT {
            get {
                return ResourceManager.GetString("NUCLEUS101_MESSAGEFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your &lt;pacakge&gt; name element in package.xml.
        /// </summary>
        internal static string NUCLEUS101_TITLE {
            get {
                return ResourceManager.GetString("NUCLEUS101_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your manifest (package.xml) file has an empty version element..
        /// </summary>
        internal static string NUCLEUS102_MESSAGEFORMAT {
            get {
                return ResourceManager.GetString("NUCLEUS102_MESSAGEFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your &lt;pacakge&gt; version element in package.xml.
        /// </summary>
        internal static string NUCLEUS102_TITLE {
            get {
                return ResourceManager.GetString("NUCLEUS102_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your manifest (package.xml) file has an invalid Id attribute (value is not a guid)..
        /// </summary>
        internal static string NUCLEUS103_MESSAGEFORMAT {
            get {
                return ResourceManager.GetString("NUCLEUS103_MESSAGEFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your &lt;package&gt; element id in package.xml.
        /// </summary>
        internal static string NUCLEUS103_TITLE {
            get {
                return ResourceManager.GetString("NUCLEUS103_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your manifest (package.xml) file has an invalid version element.  The version element must contain a version number in the format &apos;major.minor[.build[.revision]]&apos;, where build and revision are optional..
        /// </summary>
        internal static string NUCLEUS104_MESSAGEFORMAT {
            get {
                return ResourceManager.GetString("NUCLEUS104_MESSAGEFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your &lt;pacakge&gt; version element in package.xml.
        /// </summary>
        internal static string NUCLEUS104_TITLE {
            get {
                return ResourceManager.GetString("NUCLEUS104_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your project references version &apos;{1}&apos; of package &apos;{0}&apos; but your manifest (package.xml) file has a compatibility element with a minVersion of {2}, which is less than {1}.  Either update your minVersion to &apos;{1}&apos; or downgrade your reference to &apos;{0}&apos; to version &apos;{2}&apos; or less..
        /// </summary>
        internal static string NUCLEUS200_MESSAGEFORMAT {
            get {
                return ResourceManager.GetString("NUCLEUS200_MESSAGEFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your &lt;compatibilty&gt; element in package.xml.
        /// </summary>
        internal static string NUCLEUS200_TITLE {
            get {
                return ResourceManager.GetString("NUCLEUS200_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller class &apos;{0}&apos; does not have an [Extension] attribute. A Nucleus.Abstractions.Extension attribute is required to facilitate Nucleus routing..
        /// </summary>
        internal static string NUCLEUS300_MESSAGEFORMAT {
            get {
                return ResourceManager.GetString("NUCLEUS300_MESSAGEFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller class &apos;{0}&apos; does not have an [Extension] attribute..
        /// </summary>
        internal static string NUCLEUS300_TITLE {
            get {
                return ResourceManager.GetString("NUCLEUS300_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller class &apos;{0}&apos;, method &apos;{1}&apos; looks like a controller action which updates data, but neither the &apos;{0}&apos; class or the &apos;{1}&apos; method have an [Authorize] attribute. This may be a security risk because you are not checking user authorization for this action..
        /// </summary>
        internal static string NUCLEUS301_MESSAGEFORMAT {
            get {
                return ResourceManager.GetString("NUCLEUS301_MESSAGEFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing [Authorize] attribute in controller class &apos;{0}&apos; method &apos;{1}&apos;..
        /// </summary>
        internal static string NUCLEUS301_TITLE {
            get {
                return ResourceManager.GetString("NUCLEUS301_TITLE", resourceCulture);
            }
        }
    }
}
