//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nucleus.DeveloperTools.Analyzers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nucleus.DeveloperTools.Analyzers.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller class &apos;{0}&apos; does not have an [Extension] attribute. A Nucleus.Abstractions.Extension attribute is required to facilitate Nucleus routing..
        /// </summary>
        internal static string NUCL300_MESSAGEFORMAT {
            get {
                return ResourceManager.GetString("NUCL300_MESSAGEFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller class &apos;{0}&apos; does not have an [Extension] attribute..
        /// </summary>
        internal static string NUCL300_TITLE {
            get {
                return ResourceManager.GetString("NUCL300_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller class &apos;{0}&apos;, method &apos;{1}&apos; looks like a controller action which updates data, but neither the &apos;{0}&apos; class or the &apos;{1}&apos; method have an [Authorize] attribute, or another attribute which implements Microsoft.AspNetCore.Authorization.IAuthorizeData. This may be a security risk because you are not checking user authorization for this action.  Add [AllowAnonymous] to suppress this warning if you do not want to use an Authorization attribute..
        /// </summary>
        internal static string NUCL301_MESSAGEFORMAT {
            get {
                return ResourceManager.GetString("NUCL301_MESSAGEFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing [Authorize] attribute in controller class &apos;{0}&apos; method &apos;{1}&apos;..
        /// </summary>
        internal static string NUCL301_TITLE {
            get {
                return ResourceManager.GetString("NUCL301_TITLE", resourceCulture);
            }
        }
    }
}
